# Generated by Django 5.0 on 2026-03-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='shortname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
