# Generated by Django 5.0 on 2026-04-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_activity_shortname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='shortname',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
