# Generated by Django 5.0 on 2026-04-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_tag_activity_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='activity/logos/', verbose_name='Logo'),
        ),
    ]
