# Generated by Django 5.0 on 2026-04-08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0005_activity_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="location_text",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Ubicación (texto)"
            ),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE "Activity" SET "location_text" = "location" WHERE "location" IS NOT NULL;
                UPDATE "Activity" SET "location" = NULL WHERE "location" IS NOT NULL AND "location"::text !~* '^\s*\{';
            """,
            reverse_sql="""
                UPDATE "Activity" SET "location" = "location_text" WHERE "location_text" IS NOT NULL;
            """,
        ),
        migrations.AlterField(
            model_name="activity",
            name="location",
            field=models.JSONField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Coordenadas de ubicación",
            ),
        ),
    ]
