# Generated by Django 5.0 on 2026-04-09 23:45

import apps.activity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_activity_location_text_alter_activity_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.JSONField(blank=True, default=apps.activity.models.default_location_coords, null=True, verbose_name='Coordenadas de ubicación'),
        ),
    ]
