# Generated by Django 5.0 on 2026-03-29 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_activity_shortname'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailpermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='detailpermission',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='activity.activity', verbose_name='activity'),
        ),
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='DetailPermission',
        ),
    ]
