# Generated by Django 5.0 on 2026-04-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_detailpermission_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_name',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Nombre de usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
