# Generated by Django 5.0 on 2026-03-24 21:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
        ('inscription', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.CharField(max_length=150, unique=True, verbose_name='Descripcion')),
                ('concept_type', models.CharField(choices=[('I', 'INGRESO'), ('E', 'EGRESO')], default='I', max_length=1, verbose_name='Tipo de Concepto')),
                ('is_active', models.BooleanField(default=True)),
                ('is_internal', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Concepto',
                'verbose_name_plural': 'Conceptos',
                'db_table': 'Concept',
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('movement_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripcion')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Documento Referencia')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('status', models.CharField(choices=[('DRAFT', 'BORRADOR'), ('POSTED', 'CONTABILIZADO'), ('VOID', 'ANULADO')], db_index=True, default='DRAFT', max_length=10, verbose_name='Estado')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='activity.activity')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='till.concept')),
                ('inscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inscription.inscription')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inscription.paymentmethod', verbose_name='Metodo de Pago')),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='till.movement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'db_table': 'Movements',
                'indexes': [models.Index(fields=['activity', 'movement_at'], name='till_act_date_idx'), models.Index(fields=['concept', 'movement_at'], name='till_con_date_idx'), models.Index(fields=['status', 'movement_at'], name='till_sta_date_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='movement',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='till_movement_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='movement',
            constraint=models.CheckConstraint(check=models.Q(('id', models.F('reversal_of')), _negated=True), name='till_movement_not_self_reverse'),
        ),
        migrations.AddConstraint(
            model_name='movement',
            constraint=models.UniqueConstraint(condition=models.Q(('reversal_of__isnull', False)), fields=('reversal_of',), name='till_movement_one_reversal'),
        ),
    ]
