# Generated by Django 5.0 on 2026-04-09 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_alter_activity_location'),
        ('till', '0003_group_payment_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='concept_activities', to='activity.activity'),
        ),
    ]
