# Generated by Django 5.0 on 2026-04-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_alter_activity_location'),
        ('till', '0004_concept_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='description',
            field=models.CharField(max_length=150, verbose_name='Descripcion'),
        ),
        migrations.AddConstraint(
            model_name='concept',
            constraint=models.UniqueConstraint(fields=('description', 'activity'), name='unique_concept_activity', nulls_distinct=False),
        ),
    ]
