# Generated by Django 5.0 on 2026-03-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, unique=True)),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'church',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documenttype',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200, unique=True)),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'documenttype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('checkinat', models.DateTimeField(blank=True, db_column='checkinAt', null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('countgroup', models.IntegerField()),
                ('vouchergroup', models.CharField(max_length=100)),
                ('voucherpath', models.CharField(max_length=255)),
                ('voucheramount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observations', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'inscription',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paymentmethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, unique=True)),
                ('account', models.CharField(blank=True, max_length=50, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'paymentmethod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('doc_num', models.CharField(max_length=15, unique=True)),
                ('names', models.CharField(max_length=100)),
                ('lastnames', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField()),
                ('type_person', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrismaMigrations',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('checksum', models.CharField(max_length=64)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('migration_name', models.CharField(max_length=255)),
                ('logs', models.TextField(blank=True, null=True)),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('applied_steps_count', models.IntegerField()),
            ],
            options={
                'db_table': '_prisma_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(unique=True)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
