# Generated by Django 5.0 on 2026-04-08 07:48

import apps.cms.models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0004_tag_activity_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('file', models.ImageField(upload_to=apps.cms.models.cms_media_path, verbose_name='Archivo')),
                ('original_filename', models.CharField(max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_media_assets', to='activity.activity', verbose_name='Actividad')),
            ],
            options={
                'verbose_name': 'Archivo Multimedia',
                'verbose_name_plural': 'Archivos Multimedia',
                'db_table': 'cms_media_asset',
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('page_title', models.CharField(default='', max_length=200)),
                ('theme_color', models.CharField(default='#f97316', max_length=7)),
                ('language', models.CharField(default='es-PE', max_length=10)),
                ('hero_motto', models.CharField(default='', max_length=100)),
                ('hero_verse', models.TextField(default='')),
                ('hero_citation', models.CharField(default='', max_length=100)),
                ('hero_date_label', models.CharField(default='', max_length=50)),
                ('hero_background_image', models.ImageField(blank=True, null=True, upload_to=apps.cms.models.cms_hero_path, verbose_name='Imagen de fondo del Hero')),
                ('vision_title', models.CharField(default='', max_length=200)),
                ('vision_description', models.TextField(default='')),
                ('vision_feature_1_icon', models.CharField(default='', max_length=50)),
                ('vision_feature_1_label', models.CharField(default='', max_length=100)),
                ('vision_feature_2_icon', models.CharField(default='', max_length=50)),
                ('vision_feature_2_label', models.CharField(default='', max_length=100)),
                ('vision_image_1', models.ImageField(blank=True, null=True, upload_to=apps.cms.models.cms_hero_path, verbose_name='Imagen de visión 1')),
                ('vision_image_2', models.ImageField(blank=True, null=True, upload_to=apps.cms.models.cms_hero_path, verbose_name='Imagen de visión 2')),
                ('pricing_section_title', models.CharField(default='', max_length=200)),
                ('pricing_currency', models.CharField(default='S/', max_length=10)),
                ('plan_1_id', models.CharField(default='early_bird', max_length=50)),
                ('plan_1_name', models.CharField(default='', max_length=100)),
                ('plan_1_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('plan_1_original_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('plan_1_subtitle', models.CharField(default='', max_length=200)),
                ('plan_1_is_recommended', models.BooleanField(default=False)),
                ('plan_1_cta_text', models.CharField(default='', max_length=100)),
                ('plan_1_benefits', models.JSONField(default=list)),
                ('plan_2_id', models.CharField(default='group_promo', max_length=50)),
                ('plan_2_name', models.CharField(default='', max_length=100)),
                ('plan_2_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('plan_2_original_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('plan_2_subtitle', models.CharField(default='', max_length=200)),
                ('plan_2_is_recommended', models.BooleanField(default=False)),
                ('plan_2_cta_text', models.CharField(default='', max_length=100)),
                ('plan_2_whatsapp_link', models.URLField(blank=True, default='')),
                ('plan_2_benefits', models.JSONField(default=list)),
                ('location_place_name', models.CharField(default='', max_length=200)),
                ('location_address', models.CharField(default='', max_length=500)),
                ('location_city', models.CharField(default='', max_length=100)),
                ('location_description', models.TextField(default='')),
                ('location_map_url', models.URLField(blank=True, default='')),
                ('location_amenities', models.JSONField(default=list)),
                ('footer_cta_title', models.CharField(default='', max_length=200)),
                ('footer_organization', models.CharField(default='', max_length=200)),
                ('footer_year', models.IntegerField(default=2026)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cms_page', to='activity.activity', verbose_name='Actividad')),
            ],
            options={
                'verbose_name': 'Contenido de Página',
                'verbose_name_plural': 'Contenidos de Página',
                'db_table': 'cms_page_content',
            },
        ),
    ]
