# Generated by Django 5.0 on 2026-03-15 08:07

import apps.inscription.models
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('checkinat', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('P', 'PENDIENTE'), ('C', 'CONFIRMADO'), ('A', 'ASISTIO'), ('R', 'RECHAZADO'), ('E', 'ERROR')], max_length=1, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observations', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Inscripcion',
                'verbose_name_plural': 'Inscripciones',
                'db_table': 'Inscription',
            },
        ),
        migrations.CreateModel(
            name='InscriptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('vouchergroup', models.CharField(blank=True, max_length=100, null=True)),
                ('voucherfile', models.ImageField(blank=True, null=True, upload_to=apps.inscription.models.path_and_rename)),
                ('voucheramount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Grupo de Inscripcion',
                'verbose_name_plural': 'Grupos de Inscripcion',
                'db_table': 'InscriptionGroup',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, unique=True)),
                ('account', models.CharField(blank=True, max_length=50, null=True)),
                ('cci', models.CharField(blank=True, max_length=50, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('active', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Metedo de Pago',
                'verbose_name_plural': 'Metodos de Pagos',
                'db_table': 'PaymentMethod',
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('selected', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
                'db_table': 'Tarifa',
            },
        ),
    ]
