# Generated by Django 5.0 on 2026-03-15 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
        ('inscription', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_InscriptionPerson', to='person.person'),
        ),
        migrations.AddField(
            model_name='inscriptiongroup',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_InscriptionGroupActivity', to='activity.activity'),
        ),
    ]
