# Generated by Django 5.0 on 2026-03-29 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_activity_shortname'),
        ('inscription', '0004_inscriptiongroup_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_activities', to='activity.activity'),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarifas_activities', to='activity.activity'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'PENDIENTE'), ('C', 'CONFIRMADO'), ('R', 'RECHAZADO'), ('E', 'ERROR')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
