# Generated by Django 5.0 on 2026-06-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0005_paymentmethod_activity_tarifa_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
